extends: #Imports upstream linting rules
 - ./lint/eslintrc-gjs.yml
 - ./lint/eslintrc-shell.yml
parserOptions:
  sourceType: module
rules: #Override some of the upstream rules to match this codebase
  arrow-parens:
   - error
   - always
  comma-dangle:
   - error
   - never
  curly:
   - error
   - all
  jsdoc/require-jsdoc: off
  prefer-template: off
