# This workflow will test the build system, then build the extension and upload an artifact
name: Test build system and upload extension

on:
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install apt packages
      run: |
        sudo apt update
        sudo apt install --no-install-recommends make gettext gnome-shell

    - name: Test extension builds from scratch
      run: |
        make build

    - name: Test extension installs
      run: |
        make install

    - uses: actions/upload-artifact@v7
      with:
        name: caffeine@patapon.info.zip
        path: caffeine@patapon.info.zip
        archive: false

    - name: Test build area clean
      run: |
        make clean
