# Run eslint on the codebase
name: Lint codebase

on:
  pull_request:
    branches: '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install apt packages
      run: |
        sudo apt update
        sudo apt install --no-install-recommends make npm
    - name: Install eslint
      run: |
        npm install

    - name: Run linter target
      run: |
        make lint
