name: Run shellcheck

on:
  pull_request:
    branches: '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        run: |
          find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck
